[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/posts/*/*/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[build.environment]
HUGO_VERSION = "0.127.0"
TZ = "America/Denver"

[build]
publish = "public"
command = "hugo --gc --minify"
